// Generated by hand from the real shared Supabase schema (reca-app's
// migrations, cross-checked against the live project's table names via
// its PostgREST API — see plans.md "Type generation" note). This
// project's anon key can query tables but the project blocks full
// OpenAPI/OPTIONS schema introspection, so `supabase gen types
// typescript` could not be run directly; a DB connection string would
// let that run for real and should replace this file when available.
//
// Tables typed so far: missions, mission_items, mission_events,
// mission_notes, users (Auth module), plus the minimal columns of
// routes/route_contracts/employees/equipments/contracts/clients
// needed to join and display them. Other tables exist in the shared DB
// (leads, quotes, invoices, payments, ...) but are not typed here yet
// — add them as their modules are scoped, following the same
// migration-file cross-check process (docs/adr/ADR-002-operator-contracts.md).
//
// This file is committed per memory.md ("DB type generation") — do not
// hand-edit casually without re-checking against reca-app's migrations
// or a real `supabase gen types typescript` run.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      missions: {
        Row: {
          id: string
          numero: number | null
          route_id: string
          date: string
          heure_prevue: string
          heure_debut: string | null
          heure_fin: string | null
          operator_id: string | null
          equipment_id: string | null
          notes: string | null
          statut:
            | 'planifiee'
            | 'en_cours'
            | 'terminee'
            | 'terminee_avec_anomalies'
            | 'annulee'
          created_at: string
          updated_at: string
          created_by: string | null
          updated_by: string | null
          deleted_at: string | null
        }
        Insert: {
          id?: string
          numero?: number | null
          route_id: string
          date: string
          heure_prevue: string
          heure_debut?: string | null
          heure_fin?: string | null
          operator_id?: string | null
          equipment_id?: string | null
          notes?: string | null
          statut?: Database['public']['Tables']['missions']['Row']['statut']
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['missions']['Insert']>
        Relationships: []
      }
      mission_items: {
        Row: {
          id: string
          mission_id: string
          contract_id: string
          statut: 'en_attente' | 'en_cours' | 'terminee' | 'a_reprendre' | 'impossible'
          statut_operateur:
            | 'en_attente'
            | 'en_route'
            | 'en_approche'
            | 'en_cours'
            | 'depart'
            | 'terminee'
            | 'a_reprendre'
            | null
          heure_arrivee: string | null
          heure_fin: string | null
          duree_trajet_secondes: number | null
          duree_intervention_secondes: number | null
          created_at: string
          updated_at: string
          created_by: string | null
          updated_by: string | null
          deleted_at: string | null
        }
        Insert: {
          id?: string
          mission_id: string
          contract_id: string
          statut?: Database['public']['Tables']['mission_items']['Row']['statut']
          statut_operateur?: Database['public']['Tables']['mission_items']['Row']['statut_operateur']
          heure_arrivee?: string | null
          heure_fin?: string | null
          duree_trajet_secondes?: number | null
          duree_intervention_secondes?: number | null
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['mission_items']['Insert']>
        Relationships: []
      }
      mission_events: {
        Row: {
          id: string
          mission_id: string
          type:
            | 'mission_creee'
            | 'mission_debutee'
            | 'mission_pausee'
            | 'mission_reprise'
            | 'mission_terminee'
            | 'mission_terminee_avec_anomalies'
            | 'mission_fermee_de_force'
            | 'mission_annulee'
          payload: Json | null
          created_at: string
          updated_at: string
          created_by: string | null
          updated_by: string | null
          deleted_at: string | null
        }
        Insert: {
          id?: string
          mission_id: string
          type: Database['public']['Tables']['mission_events']['Row']['type']
          payload?: Json | null
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['mission_events']['Insert']>
        Relationships: []
      }
      mission_notes: {
        Row: {
          id: string
          mission_id: string
          message: string
          created_at: string
          updated_at: string
          created_by: string | null
          updated_by: string | null
          deleted_at: string | null
        }
        Insert: {
          id?: string
          mission_id: string
          message: string
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['mission_notes']['Insert']>
        Relationships: []
      }
      routes: {
        Row: {
          id: string
          nom: string
          couleur: string
          operator_id: string | null
          equipment_id: string | null
          created_at: string
          updated_at: string
          created_by: string | null
          updated_by: string | null
          deleted_at: string | null
        }
        Insert: {
          id?: string
          nom: string
          couleur: string
          operator_id?: string | null
          equipment_id?: string | null
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['routes']['Insert']>
        Relationships: []
      }
      route_contracts: {
        Row: {
          id: string
          route_id: string
          contract_id: string
          ordre: number
          created_at: string
          updated_at: string
          created_by: string | null
          updated_by: string | null
          deleted_at: string | null
        }
        Insert: {
          id?: string
          route_id: string
          contract_id: string
          ordre?: number
          created_at?: string
          updated_at?: string
          created_by?: string | null
          updated_by?: string | null
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['route_contracts']['Insert']>
        Relationships: []
      }
      employees: {
        Row: {
          id: string
          user_id: string | null
          prenom: string
          nom: string
          telephone: string | null
          courriel: string | null
          poste: string | null
          role: string | null
          actif: boolean
          deleted_at: string | null
        }
        Insert: {
          id?: string
          user_id?: string | null
          prenom: string
          nom: string
          telephone?: string | null
          courriel?: string | null
          poste?: string | null
          role?: string | null
          actif?: boolean
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['employees']['Insert']>
        Relationships: []
      }
      equipments: {
        Row: {
          id: string
          numero: string | null
          nom: string
          categorie: string | null
          statut: 'disponible' | 'en_operation' | 'entretien' | 'brise'
          deleted_at: string | null
        }
        Insert: {
          id?: string
          numero?: string | null
          nom: string
          categorie?: string | null
          statut?: Database['public']['Tables']['equipments']['Row']['statut']
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['equipments']['Insert']>
        Relationships: []
      }
      contracts: {
        Row: {
          id: string
          numero: string | null
          client_id: string
          type: string | null
          statut: 'actif' | 'en_attente' | 'expire' | 'annule'
          prix: number | null
          deleted_at: string | null
        }
        Insert: {
          id?: string
          numero?: string | null
          client_id: string
          type?: string | null
          statut?: Database['public']['Tables']['contracts']['Row']['statut']
          prix?: number | null
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['contracts']['Insert']>
        Relationships: []
      }
      clients: {
        Row: {
          id: string
          numero: string | null
          prenom: string | null
          nom: string | null
          entreprise: string | null
          adresse: string | null
          ville: string | null
          type_client: string | null
          deleted_at: string | null
        }
        Insert: {
          id?: string
          numero?: string | null
          prenom?: string | null
          nom?: string | null
          entreprise?: string | null
          adresse?: string | null
          ville?: string | null
          type_client?: string | null
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['clients']['Insert']>
        Relationships: []
      }
      users: {
        Row: {
          id: string
          email: string
          role: 'administrateur' | 'employe' | 'operateur'
          actif: boolean
          nom: string | null
          theme: 'clair' | 'sombre'
          derniere_connexion: string | null
          deleted_at: string | null
        }
        Insert: {
          id: string
          email: string
          role?: Database['public']['Tables']['users']['Row']['role']
          actif?: boolean
          nom?: string | null
          theme?: Database['public']['Tables']['users']['Row']['theme']
          derniere_connexion?: string | null
          deleted_at?: string | null
        }
        Update: Partial<Database['public']['Tables']['users']['Insert']>
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      update_own_theme: {
        Args: { new_theme: 'clair' | 'sombre' }
        Returns: undefined
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
